import type { SeoPage } from './types'

// Country hub pages — localize the pitch for each market so search engines and
// AI assistants can answer country-specific queries about crypto cashout.

export const countryPages: SeoPage[] = [
  {
    slug: 'nigeria',
    kind: 'country',
    path: '/nigeria',
    metaTitle: 'SureXend in Nigeria — USDC to Naira, Airtime, Bills & Bank (2026)',
    metaDescription: 'Use USDC in Nigeria: convert to naira at a live rate, withdraw to any bank, buy MTN/Airtel/GLO/9mobile airtime and pay DSTV & electricity. Free to start.',
    keywords: ['surexend nigeria', 'usdc naira', 'buy airtime with crypto nigeria', 'pay bills with crypto nigeria', 'crypto to bank nigeria'],
    h1: 'SureXend in Nigeria',
    intro:
      "SureXend is a stablecoin wallet built for Nigeria — receive USDC from anywhere, convert to naira at a live rate, withdraw to any bank, and pay airtime, data, DSTV and electricity without ever cashing out.",
    sections: [
      { type: 'p', text: "Nigerians receive more in crypto than almost anyone else on the continent. SureXend makes that USDC genuinely useful: it converts at a transparent live rate, pays out to Nigerian banks in minutes, and lets you spend directly on the bills and airtime you buy every week." },
      { type: 'h2', text: 'What you can do with SureXend in Nigeria' },
      { type: 'list', items: [
        'Convert USDC to naira at a live rate — no P2P vendors.',
        'Withdraw to any Nigerian bank via instant transfer.',
        'Buy MTN, Airtel, GLO and 9mobile airtime & data from your USDC balance.',
        'Pay electricity, DSTV, GOtv and water bills with crypto.',
        'Receive USDC payments from international clients and hold dollars safely.',
      ] },
      { type: 'h2', text: 'Why Nigerians use stablecoins' },
      { type: 'table', head: ['Use case', 'How SureXend helps'], rows: [
        ['Freelance income', 'Get paid in USDC, convert what you need'],
        ['Sending money home', 'Family converts & spends in the app'],
        ['Protecting savings', 'Hold dollars instead of losing to inflation'],
        ['Everyday spend', 'Airtime, data, electricity and TV with USDC'],
      ] },
      { type: 'callout', title: 'Built for Nigerian speed', text: 'Instant bank transfers, seconds-fast airtime, and 24/7 operation — so your money moves when you do, not on bank hours.' },
    ],
    faq: [
      { q: 'Is SureXend available in Nigeria?', a: 'Yes. Nigeria is SureXend\u2019s flagship market — naira balances, Nigerian bank withdrawals and Nigerian bill/airtime providers are all supported.' },
      { q: 'How do I withdraw naira to my bank on SureXend?', a: 'Add your bank account once, convert USDC to naira at the live rate, and withdraw. The transfer clears in minutes via instant bank transfer.' },
      { q: 'Can I buy airtime with USDC in Nigeria?', a: 'Yes. MTN, Airtel, GLO and 9mobile airtime and data are paid directly from your USDC balance.' },
      { q: 'What KYC does SureXend require in Nigeria?', a: 'A short verification on signup. Higher verification levels unlock higher deposit and withdrawal limits.' },
      { q: 'Is using crypto legal in Nigeria?', a: 'Yes, crypto and stablecoins are legal for personal use. Use a compliant platform and keep your transaction records.' },
    ],
    ctaTitle: 'Make your USDC work in Nigeria',
    ctaText: 'Create your free SureXend wallet today — naira, airtime and bills in one app.',
    related: ['/convert-usdc-to-naira', '/buy-airtime-with-crypto', '/blog/how-to-sell-usdc-for-naira'],
    datePublished: '2026-02-20',
    dateModified: '2026-08-01',
    author: 'SureXend Editorial',
    readingTime: '4 min read',
    priority: 0.8,
  },
  {
    slug: 'kenya',
    kind: 'country',
    path: '/kenya',
    metaTitle: 'SureXend in Kenya — USDC to KES, Mobile Money & More (2026)',
    metaDescription: 'Use USDC in Kenya: convert to shillings at a live rate, withdraw to your bank or mobile money, and spend on everyday bills. Free to start on SureXend.',
    keywords: ['surexend kenya', 'usdc kes', 'crypto to mobile money kenya', 'sell usdc kenya', 'stablecoin kenya'],
    h1: 'SureXend in Kenya',
    intro:
      "Kenya runs on mobile money — and your crypto should plug straight into it. SureXend converts USDC to shillings at a live rate and pays out to your bank or mobile money, so your dollars work where you live.",
    sections: [
      { type: 'p', text: "Kenya has one of the most advanced digital-money ecosystems in Africa. SureXend adds stablecoin to that mix: receive USDC from anywhere, hold it in dollars, and convert to KES the moment you need it — with payout to the bank or mobile-money account you already use." },
      { type: 'h2', text: 'What you can do with SureXend in Kenya' },
      { type: 'list', items: [
        'Convert USDC to Kenyan shillings at a live rate.',
        'Withdraw to your bank or mobile money.',
        'Hold your income in dollars instead of losing to inflation.',
        'Receive USDC payments from clients and freelancers overseas.',
      ] },
      { type: 'h2', text: 'Why hold USDC in Kenya' },
      { type: 'table', head: ['Use case', 'How SureXend helps'], rows: [
        ['Remote work income', 'Get paid in USDC, convert when needed'],
        ['Mobile money savings', 'Shift value in and out of shillings fast'],
        ['Business payments', 'Settle suppliers with stablecoin rails'],
      ] },
      { type: 'callout', title: 'Mobile-money native', text: 'Payout is designed to land where you already transact — no need to open a new bank just to cash out your crypto.' },
    ],
    faq: [
      { q: 'Is SureXend available in Kenya?', a: 'Yes. SureXend supports Kenyan shillings with bank and mobile-money payout options.' },
      { q: 'Can I withdraw USDC to mobile money in Kenya?', a: 'Yes, mobile money payout is supported alongside bank transfers.' },
      { q: 'How is the USDC to KES rate set?', a: 'A live market rate is shown before you confirm every conversion.' },
      { q: 'Is crypto legal in Kenya?', a: 'Crypto is legal for personal use in Kenya. SureXend operates in line with local regulations in every market.' },
    ],
    ctaTitle: 'Bring your crypto into your Kenyan life',
    ctaText: 'Create a wallet, deposit USDC, and cash out to your bank or mobile money.',
    related: ['/crypto-to-bank-africa', '/ghana', '/south-africa'],
    datePublished: '2026-03-05',
    dateModified: '2026-08-01',
    author: 'SureXend Editorial',
    readingTime: '3 min read',
    priority: 0.75,
  },
  {
    slug: 'ghana',
    kind: 'country',
    path: '/ghana',
    metaTitle: 'SureXend in Ghana — USDC to Cedis, Mobile Money & More (2026)',
    metaDescription: 'Use USDC in Ghana: convert to cedis at a live rate, withdraw to your bank or mobile money, and keep your income in dollars. Free to start on SureXend.',
    keywords: ['surexend ghana', 'usdc ghs', 'sell usdc ghana', 'crypto to mobile money ghana', 'stablecoin ghana'],
    h1: 'SureXend in Ghana',
    intro:
      "Turn your USDC into cedis that work in Accra, Kumasi or anywhere in Ghana. SureXend converts at a live rate and pays out to your bank or mobile money — with the option to hold your value in dollars.",
    sections: [
      { type: 'p', text: "Ghana\u2019s mobile money market is one of the fastest-growing in Africa. SureXend lets you receive USDC from international clients, hold it in dollars, and convert to GHS when you need to pay for life in cedis." },
      { type: 'h2', text: 'What you can do with SureXend in Ghana' },
      { type: 'list', items: [
        'Convert USDC to Ghanaian cedis at a live rate.',
        'Withdraw to your bank or mobile money.',
        'Receive USDC payments from clients abroad.',
        'Protect your earnings from cedi depreciation.',
      ] },
      { type: 'h2', text: 'Why Ghanaians hold stablecoins' },
      { type: 'table', head: ['Use case', 'How SureXend helps'], rows: [
        ['Freelance income', 'Keep client payments in stable USDC'],
        ['Savings', 'Hold dollars instead of cedi exposure'],
        ['Business', 'Settle payments with stablecoin rails'],
      ] },
      { type: 'callout', title: 'Local payouts, global money', text: 'The cedi is strong when you convert and weak when you don\u2019t have to. With USDC you choose the moment — that\u2019s real control.' },
    ],
    faq: [
      { q: 'Is SureXend available in Ghana?', a: 'Yes. SureXend supports Ghanaian cedis with bank and mobile-money payouts.' },
      { q: 'Can I cash out USDC to mobile money in Ghana?', a: 'Yes, mobile money payout is supported alongside bank transfers.' },
      { q: 'How do I convert USDC to cedis?', a: 'Open Convert, choose USDC to GHS, review the live rate and confirm. Your cedi balance updates instantly.' },
      { q: 'Is crypto legal in Ghana?', a: 'Crypto is legal for personal use in Ghana. Use a compliant platform and keep records of your transactions.' },
    ],
    ctaTitle: 'Make your USDC useful in Ghana',
    ctaText: 'Create a free wallet and convert at a live rate — cash out to bank or mobile money.',
    related: ['/crypto-to-bank-africa', '/kenya', '/nigeria'],
    datePublished: '2026-03-10',
    dateModified: '2026-08-01',
    author: 'SureXend Editorial',
    readingTime: '3 min read',
    priority: 0.75,
  },
  {
    slug: 'south-africa',
    kind: 'country',
    path: '/south-africa',
    metaTitle: 'SureXend in South Africa — USDC to Rand & Bank Payouts (2026)',
    metaDescription: 'Use USDC in South Africa: convert to rands at a live rate and withdraw to your bank. Hold your income in dollars with SureXend.',
    keywords: ['surexend south africa', 'usdc zar', 'sell usdc south africa', 'crypto to bank south africa', 'stablecoin south africa'],
    h1: 'SureXend in South Africa',
    intro:
      "Convert USDC to rands at a live rate and withdraw to your South African bank. SureXend gives you dollar-stable value and rand liquidity — the best of both worlds.",
    sections: [
      { type: 'p', text: "South Africa has mature banking and a growing crypto community. SureXend sits in the middle: receive USDC from anywhere, keep your value in dollars, and convert to ZAR at a live rate when you need rands for life and business." },
      { type: 'h2', text: 'What you can do with SureXend in South Africa' },
      { type: 'list', items: [
        'Convert USDC to South African rands at a live rate.',
        'Withdraw to your bank account.',
        'Receive USDC payments from clients and employers abroad.',
        'Hold your savings in dollar-pegged stablecoin.',
      ] },
      { type: 'h2', text: 'Why South Africans use stablecoin' },
      { type: 'table', head: ['Use case', 'How SureXend helps'], rows: [
        ['Remote income', 'Get paid in USDC from international employers'],
        ['Travel & e-commerce', 'Hold dollars, convert when needed'],
        ['Savings', 'Dollar exposure without leaving the banking system'],
      ] },
      { type: 'callout', title: 'Bank-grade simplicity', text: 'A regulated, secure wallet that pays out to the banks you already use — no complicated self-custody setup required.' },
    ],
    faq: [
      { q: 'Is SureXend available in South Africa?', a: 'Yes. SureXend supports South African rands with bank payout.' },
      { q: 'Can I withdraw USDC to my South African bank?', a: 'Yes. Add your bank account, convert USDC to rands at a live rate, and withdraw.' },
      { q: 'Is crypto legal in South Africa?', a: 'Yes. South Africa regulates crypto-asset service providers, and crypto is legal for personal use.' },
      { q: 'How fast is a rand withdrawal?', a: 'Conversion is instant and the bank payout processes quickly, depending on your bank\u2019s settlement times.' },
    ],
    ctaTitle: 'Your USDC, working in rands',
    ctaText: 'Create a wallet, deposit USDC, and withdraw to your South African bank.',
    related: ['/crypto-to-bank-africa', '/nigeria', '/kenya'],
    datePublished: '2026-03-15',
    dateModified: '2026-08-01',
    author: 'SureXend Editorial',
    readingTime: '3 min read',
    priority: 0.75,
  },
]