import type { SeoPage } from './types'

// Commercial keyword landing pages — the money pages. Each one targets a
// transaction intent ("sell USDC", "buy airtime with crypto", "send money to
// Nigeria") and funnels to the app.

export const landingPages: SeoPage[] = [
  {
    slug: 'convert-usdc-to-naira',
    kind: 'landing',
    path: '/convert-usdc-to-naira',
    metaTitle: 'Convert USDC to Naira Instantly (2026) | SureXend',
    metaDescription: 'Sell USDC for naira at a live rate and withdraw to any Nigerian bank in minutes. No P2P vendors, no hidden fees. Start with SureXend today.',
    keywords: ['USDC to naira', 'sell USDC for naira', 'convert USDC to NGN', 'usdc to bank account nigeria', 'stablecoin to naira'],
    h1: 'Convert USDC to Naira, Instantly',
    intro:
      "SureXend turns your USDC into naira you can actually spend — no P2P vendors, no waiting on a stranger to release payment. Deposit USDC to your SureXend wallet, convert at a live rate, and withdraw to any Nigerian bank account in minutes.",
    sections: [
      { type: 'p', text: "Freelancers, remote workers and traders receive USDC every week. The old way of converting it — meeting a P2P buyer, sending crypto first, hoping they release the naira — is slow and full of scam risk. SureXend removes the middleman: the conversion runs on our own rails, so the rate you see is the rate you get." },
      { type: 'h2', text: 'How to sell USDC for naira on SureXend' },
      { type: 'list', items: [
        'Sign up free and complete a one-screen KYC (takes minutes, not days).',
        'Deposit USDC into your SureXend wallet — it supports the networks you already use.',
        'Open Convert, choose USD → NGN, and check the live rate before you confirm.',
        'Tap convert. Your naira balance updates instantly at the locked rate.',
        'Withdraw to any Nigerian bank, or spend it straight on airtime, data and bills inside the app.',
      ] },
      { type: 'callout', title: 'Why people convert USDC with SureXend', text: 'Live, transparent rates instead of P2P spreads. Zero hidden fees. Bank withdrawals that clear in minutes via NIBSS instant transfer. And no vendor who can ghost you after you send.' },
      { type: 'h2', text: 'USDC vs P2P selling: the real difference' },
      { type: 'table', head: ['', 'P2P (vendor)', 'SureXend'], rows: [
        ['Counterparty', 'Stranger you must trust', 'None — automated'],
        ['Rate', 'Spread set by vendor', 'Live market rate'],
        ['Risk', 'Release scam, reversal', 'No middleman to fail'],
        ['Speed', 'Minutes to hours', 'Minutes'],
        ['Fee', 'Often hidden', 'Transparent, shown upfront'],
      ] },
      { type: 'p', text: "Because USDC is pegged 1:1 to the US dollar, you always know exactly what you're converting — there's no price volatility between deposit and payout like there is with Bitcoin." },
    ],
    faq: [
      { q: 'How long does it take to convert USDC to naira on SureXend?', a: 'The conversion itself is instant once your USDC deposit confirms on the blockchain. Withdrawing the naira to your Nigerian bank typically clears in minutes via NIBSS instant transfer.' },
      { q: 'Is it safe to sell USDC for naira online?', a: 'Yes, when you use a platform with automated rails. Unlike P2P, there is no human counterparty who can disappear after you send your coins. SureXend converts your USDC itself and pushes the naira to your balance, then to your bank.' },
      { q: 'Can I receive USDC payments from abroad and get naira automatically?', a: 'Yes. Give your international client your SureXend USDC wallet address. When they send, your balance updates and you can convert to naira or withdraw at your pace.' },
      { q: 'Which networks does SureXend support for USDC deposits?', a: 'The wallet accepts USDC on the major networks you already use. Always double-check the network in your sending wallet matches your SureXend deposit address to avoid losing funds.' },
      { q: 'What is the current USDC to naira rate?', a: 'Rates move with the market. SureXend shows a live rate before you confirm every conversion, so you see exactly how many naira you will receive — no surprises.' },
    ],
    ctaTitle: 'Turn your USDC into spendable naira',
    ctaText: 'Create your free SureXend wallet and convert at a live rate — no P2P, no waiting.',
    related: ['/blog/how-to-sell-usdc-for-naira', '/withdraw-usdc-to-bank', '/blog/usdc-vs-usdt-nigeria'],
    datePublished: '2026-01-15',
    dateModified: '2026-08-01',
    author: 'SureXend Editorial',
    readingTime: '4 min read',
    priority: 0.9,
  },
  {
    slug: 'buy-airtime-with-crypto',
    kind: 'landing',
    path: '/buy-airtime-with-crypto',
    metaTitle: 'Buy Airtime with Crypto (2026) — MTN, Airtel, GLO, 9mobile | SureXend',
    metaDescription: 'Top up MTN, Airtel, GLO or 9mobile airtime and data with USDC. No cashing out, no extra app. Buy airtime with crypto on SureXend in seconds.',
    keywords: ['buy airtime with crypto', 'airtime with usdc', 'buy airtime with bitcoin nigeria', 'top up phone with crypto', 'mtn airtime with crypto'],
    h1: 'Buy Airtime with Crypto — In Seconds',
    intro:
      "Stop cashing out your crypto just to top up your phone. On SureXend you buy MTN, Airtel, GLO and 9mobile airtime and data directly from your USDC balance — one app, no bank detour, credited in seconds.",
    sections: [
      { type: 'p', text: "Airtime is the most common everyday spend in Nigeria, and it's the easiest place to start using crypto like cash. With SureXend you skip the whole sell → wait → withdraw → buy chain. Your USDC balance becomes the thing you pay with, and the airtime lands on the number you choose almost instantly." },
      { type: 'h2', text: 'How to buy airtime with crypto' },
      { type: 'list', items: [
        'Open the SureXend app and make sure your USDC balance covers the top-up.',
        'Tap Bills, then Airtime.',
        'Enter the phone number, choose the network (MTN, Airtel, GLO or 9mobile).',
        'Pick the amount, confirm with your secure PIN or biometrics.',
        'Done — the airtime reflects within seconds, for your line or anyone you send it to.',
      ] },
      { type: 'h2', text: 'Airtime & data on every major network' },
      { type: 'table', head: ['Network', 'Airtime', 'Data bundles'], rows: [
        ['MTN', 'Yes', 'Yes'],
        ['Airtel', 'Yes', 'Yes'],
        ['GLO', 'Yes', 'Yes'],
        ['9mobile', 'Yes', 'Yes'],
      ] },
      { type: 'callout', title: 'Why buy airtime with USDC instead of cashing out', text: 'You avoid bank delays and conversion fees, your crypto stays in dollars until the moment you spend, and you never sit on naira you have to manage separately.' },
      { type: 'h2', text: 'Send airtime to family in seconds' },
      { type: 'p', text: "Sending airtime to a relative back home is one of the fastest, most reliable ways to help — no recipient bank account needed, no pickup points, no fee on their side. Just their phone number. It's a genuinely useful reason to keep part of your savings in stablecoin." },
    ],
    faq: [
      { q: 'Can I buy airtime with USDC on SureXend?', a: 'Yes. Airtime and data purchases are paid directly from your USDC balance. You do not need to convert to naira first or withdraw to a bank.' },
      { q: 'Which networks can I buy airtime for?', a: 'MTN, Airtel, GLO and 9mobile — the four major Nigerian networks — for both airtime and data bundles.' },
      { q: 'How fast is airtime delivered when I pay with crypto?', a: 'Airtime is credited to the number within seconds after you confirm the transaction, just like a normal airtime purchase.' },
      { q: 'Can I buy airtime for someone else\u2019s number?', a: 'Yes. You enter any Nigerian number — your own or someone else\u2019s — so you can top up family and friends abroad.' },
      { q: 'Is there a hidden fee to buy airtime with crypto?', a: 'No. The price you see before you confirm is what you pay, and it\u2019s deducted from your USDC balance at a live, transparent rate.' },
    ],
    ctaTitle: 'Spend your USDC on airtime today',
    ctaText: 'Download SureXend and top up MTN, Airtel, GLO or 9mobile in seconds.',
    related: ['/blog/buy-airtime-with-crypto', '/pay-bills-with-crypto', '/nigeria'],
    datePublished: '2026-01-20',
    dateModified: '2026-08-01',
    author: 'SureXend Editorial',
    readingTime: '4 min read',
    priority: 0.9,
  },
  {
    slug: 'send-money-to-nigeria',
    kind: 'landing',
    path: '/send-money-to-nigeria',
    metaTitle: 'Send Money to Nigeria from Abroad (2026) — USD to NGN in Minutes | SureXend',
    metaDescription: 'Send money to Nigeria at a live exchange rate with no bank middleman. Your family gets naira fast — or keeps it in USDC. Compare vs Wise, Remitly & Western Union.',
    keywords: ['send money to nigeria', 'send money from usa to nigeria', 'usd to ngn', 'money transfer to nigeria', 'send usdc to nigeria'],
    h1: 'Send Money to Nigeria, Without the Bank Fees',
    intro:
      "The cheapest way to send money home is the one with the least middlemen. SureXend lets you send USDC from anywhere in the world, and your family in Nigeria gets it instantly — to convert to naira, pay bills, buy airtime, or keep it in dollars.",
    sections: [
      { type: 'p', text: "Traditional remittance takes a 5-10% cut in fees and exchange-rate markup, and your family still waits days. With SureXend, the money travels as USDC on the blockchain — near-instant settlement, a live conversion rate, and a naira balance your recipient can spend immediately or withdraw to any Nigerian bank." },
      { type: 'h2', text: 'How sending money to Nigeria works' },
      { type: 'list', items: [
        'Send USDC to your family member\u2019s SureXend wallet address (from any wallet or exchange).',
        'The transfer confirms on-chain — typically within minutes, not days.',
        'Your family member converts to naira at a live rate right inside the app.',
        'They spend on airtime, data and bills, or withdraw to any Nigerian bank.',
      ] },
      { type: 'h2', text: 'USDC remittance vs traditional transfer services' },
      { type: 'table', head: ['Factor', 'Bank transfer / Wise', 'SureXend (USDC)'], rows: [
        ['Settlement time', 'Hours to 2 days', 'Minutes on-chain'],
        ['Exchange-rate markup', 'Often 0.5-2%+', 'Live rate, shown upfront'],
        ['Recipient options', 'Usually bank only', 'Bank, bills, airtime, or keep in dollars'],
        ['Geo-restrictions', 'Corridor-dependent', 'Works from anywhere'],
      ] },
      { type: 'callout', title: 'A dollar that arrives whole', text: 'Because USDC holds its 1:1 dollar peg, the value you send is the value that arrives. Your family decides when to convert — so they can wait for a better rate instead of being forced to sell at whatever the bank offers.' },
      { type: 'h2', text: 'For freelancers: get paid in dollars, spend in naira' },
      { type: 'p', text: "Upwork, Fiverr and international clients can pay you in USDC directly. You hold the dollars, convert what you need for monthly expenses, and keep the rest growing in value instead of sitting in a bank account losing to inflation." },
    ],
    faq: [
      { q: 'What is the cheapest way to send money to Nigeria?', a: 'Generally, services with the least middlemen and a transparent exchange rate. Sending USDC on-chain and converting at a live rate avoids bank rails and markup, which makes it one of the most cost-effective options.' },
      { q: 'How long does it take to receive money sent with crypto?', a: 'The USDC transfer confirms on the blockchain in minutes (exact time depends on the network). Conversion to naira and bank withdrawal then happen inside SureXend, usually within minutes.' },
      { q: 'Can my family in Nigeria use the money without a bank account?', a: 'Yes. They can spend the naira balance directly on airtime, data and bill payments inside SureXend, so no bank account is required for everyday use.' },
      { q: 'Is it cheaper than Wise or Remitly?', a: 'The cost depends on your amount and the network fee you pay to send the USDC. Because SureXend uses a live rate with no bank middleman, total cost is often lower — and your recipient can time the conversion to naira for a better rate.' },
      { q: 'Is sending money to Nigeria with crypto legal?', a: 'Cryptocurrency and stablecoins are legal for personal use in Nigeria. As with any financial service, use a licensed, compliant platform and keep records of your transactions.' },
    ],
    ctaTitle: 'Send money home that actually arrives whole',
    ctaText: 'Create a free SureXend wallet for you and your family — send USDC, convert at a live rate.',
    related: ['/blog/send-money-from-us-to-nigeria-crypto', '/convert-usdc-to-naira', '/blog/how-to-receive-usd-payments-from-abroad'],
    datePublished: '2026-02-01',
    dateModified: '2026-08-01',
    author: 'SureXend Editorial',
    readingTime: '5 min read',
    priority: 0.9,
  },
  {
    slug: 'pay-bills-with-crypto',
    kind: 'landing',
    path: '/pay-bills-with-crypto',
    metaTitle: 'Pay Bills with Crypto: Electricity, TV, Data, Water (2026) | SureXend',
    metaDescription: 'Pay DSTV, electricity, water, data and airtime with USDC. No cashing out, no queues, all in one app. Pay your bills with crypto on SureXend.',
    keywords: ['pay bills with crypto', 'pay dstv with crypto', 'pay electricity with usdc', 'pay cable tv with bitcoin', 'crypto bill payment nigeria'],
    h1: 'Pay Your Bills with Crypto',
    intro:
      "Electricity, DSTV, water, data and airtime — all payable with USDC on SureXend. Skip the cash-out and skip the queue. Pick a bill, pay with crypto, and get it settled in seconds.",
    sections: [
      { type: 'p', text: "Living on crypto means your everyday bills should be payable the same way. SureXend turns your USDC balance into a real payment method for the services you already pay for monthly — no converting to naira first, no bank app, no standing in line." },
      { type: 'h2', text: 'What you can pay with crypto' },
      { type: 'table', head: ['Bill type', 'Examples', 'Paid with USDC'], rows: [
        ['Airtime & data', 'MTN, Airtel, GLO, 9mobile', 'Yes'],
        ['Electricity', 'Prepaid & postpaid providers', 'Yes'],
        ['Cable TV', 'DSTV, GOtv, Startimes', 'Yes'],
        ['Water', 'Supported providers', 'Yes'],
      ] },
      { type: 'h2', text: 'How bill payments work' },
      { type: 'list', items: [
        'Open Bills in the SureXend app.',
        'Choose your bill category and provider.',
        'Enter the details — meter number, smart card number, or phone number.',
        'Confirm the amount; it\u2019s deducted from your USDC balance at a live rate.',
        'You get instant confirmation, and the bill is settled.',
      ] },
      { type: 'callout', title: 'Why pay bills with stablecoin', text: 'Your money keeps its dollar value until the second you spend it, there\u2019s no naira to manage separately, and you have a clean digital record of every payment for budgeting.' },
      { type: 'h2', text: 'Never miss a payment again' },
      { type: 'p', text: "Set a reminder, keep a small USDC buffer for fixed monthly bills, and pay from anywhere — abroad or at home. When a bill is due, it's settled in seconds, whether you're in Lagos or London." },
    ],
    faq: [
      { q: 'Can I pay DSTV with crypto?', a: 'Yes. Cable TV subscriptions including DSTV are supported. Enter your smart card number, pick a plan, and pay with your USDC balance.' },
      { q: 'Can I pay electricity with USDC?', a: 'Yes. Both prepaid and postpaid electricity are supported. Enter your meter or account number and the payment settles instantly.' },
      { q: 'Do I need to convert my crypto to naira first?', a: 'No. Bills are paid directly from your USDC balance at a live rate. There is no separate conversion step.' },
      { q: 'Is paying bills with crypto safe?', a: 'Yes. Your balance is protected with a secure PIN and biometric authentication, and every payment is recorded so you can track spend.' },
      { q: 'Which bill types are supported?', a: 'Airtime, data, electricity, cable TV (DSTV, GOtv, Startimes) and water across supported providers.' },
    ],
    ctaTitle: 'Turn USDC into every bill you owe',
    ctaText: 'Download SureXend, fund with USDC, and pay electricity, TV, data and airtime in seconds.',
    related: ['/blog/pay-bills-with-crypto', '/buy-airtime-with-crypto', '/blog/what-is-a-stablecoin'],
    datePublished: '2026-02-10',
    dateModified: '2026-08-01',
    author: 'SureXend Editorial',
    readingTime: '4 min read',
    priority: 0.85,
  },
  {
    slug: 'withdraw-usdc-to-bank',
    kind: 'landing',
    path: '/withdraw-usdc-to-bank',
    metaTitle: 'Withdraw USDC to Your Bank Account (2026) | SureXend',
    metaDescription: 'Withdraw crypto to your Nigerian bank account in minutes. Convert USDC to naira at a live rate and get paid out via instant bank transfer with SureXend.',
    keywords: ['withdraw usdc to bank', 'withdraw crypto to bank account', 'usdc to naira bank', 'cash out usdc', 'crypto to bank account nigeria'],
    h1: 'Withdraw USDC to Your Bank',
    intro:
      "Convert USDC to naira and have it in your Nigerian bank account within minutes. SureXend pays out via instant bank transfer — add your account once, withdraw anytime.",
    sections: [
      { type: 'p', text: "Holding USDC is great for keeping value — but bills, rent and life are paid in naira. SureXend is the bridge between the two: convert at a live rate and withdraw to your bank in minutes, 24/7, without a P2P vendor in the middle." },
      { type: 'h2', text: 'How to withdraw USDC to your bank' },
      { type: 'list', items: [
        'Add your Nigerian bank account once in the Withdraw section.',
        'Choose the amount of USDC to convert.',
        'Review the live naira rate before you confirm.',
        'Confirm with your PIN or biometrics.',
        'The naira lands in your bank via instant transfer — typically within minutes.',
      ] },
      { type: 'h2', text: 'Withdrawal speed & reliability' },
      { type: 'table', head: ['Step', 'Typical time'], rows: [
        ['USDC conversion', 'Instant'],
        ['Bank transfer (NIBSS instant)', 'Minutes'],
        ['Money available to spend', 'Immediately on arrival'],
      ] },
      { type: 'callout', title: 'Cash out on your own schedule', text: 'Since USDC is pegged to the dollar, you can hold it safely and withdraw when the rate suits you — instead of being forced to sell at a bad time because money is already in your bank.' },
      { type: 'h2', text: 'Keep a balance for everyday spend' },
      { type: 'p', text: "You don't have to withdraw everything. Keep part of your balance as USDC for airtime, bills and conversions, and withdraw only what you need for cash — the best of both worlds." },
    ],
    faq: [
      { q: 'How fast can I withdraw USDC to my bank?', a: 'The USDC-to-naira conversion is instant, and the bank transfer clears in minutes via NIBSS instant transfer.' },
      { q: 'Can I withdraw to any Nigerian bank?', a: 'Yes. Withdrawal works with commercial banks and fintech wallets across Nigeria — add your account once and reuse it.' },
      { q: 'Is there a minimum withdrawal amount?', a: 'Withdrawal limits depend on your account verification level. Higher KYC levels unlock higher limits.' },
      { q: 'Is it safe to withdraw crypto to my bank?', a: 'Yes. SureXend uses bank-grade security, and withdrawals are protected by your PIN and biometric authentication so only you can move money.' },
      { q: 'Why should I keep USDC instead of just naira?', a: 'USDC holds its dollar value, so your savings don\u2019t erode with local inflation. Withdraw to naira only when you need cash, and convert when the rate is good.' },
    ],
    ctaTitle: 'Your crypto, cashed out in minutes',
    ctaText: 'Add your bank, convert at a live rate, and withdraw whenever you need.',
    related: ['/convert-usdc-to-naira', '/blog/how-to-sell-usdc-for-naira', '/nigeria'],
    datePublished: '2026-02-15',
    dateModified: '2026-08-01',
    author: 'SureXend Editorial',
    readingTime: '4 min read',
    priority: 0.85,
  },
  {
    slug: 'crypto-to-bank-africa',
    kind: 'landing',
    path: '/crypto-to-bank-africa',
    metaTitle: 'Crypto to Bank in Africa: Nigeria, Kenya, Ghana & More (2026) | SureXend',
    metaDescription: 'Turn USDC into local currency and withdraw to banks and mobile money across Africa. Nigeria, Kenya, Ghana and more. Live rates, no middlemen, instant.',
    keywords: ['crypto to bank africa', 'usdc to mobile money', 'crypto cashout kenya', 'stablecoin ghana', 'crypto to local currency africa'],
    h1: 'Crypto to Bank, Across Africa',
    intro:
      "Wherever you are in Africa, your USDC should work like money. SureXend converts stablecoin to local currency and pays out to banks and mobile money — live rates, no vendor, instant settlement.",
    sections: [
      { type: 'p', text: "Africa runs on local money: naira, cedis, shillings, rand — and increasingly mobile money. SureXend bridges stablecoin and local currency so you can receive USDC from anywhere in the world and spend or withdraw it wherever you live." },
      { type: 'h2', text: 'Supported countries & payout methods' },
      { type: 'table', head: ['Country', 'Local currency', 'Payout method'], rows: [
        ['Nigeria', 'NGN (naira)', 'Bank transfer, in-app bills & airtime'],
        ['Kenya', 'KES (shilling)', 'Bank & mobile money'],
        ['Ghana', 'GHS (cedi)', 'Bank & mobile money'],
        ['South Africa', 'ZAR (rand)', 'Bank transfer'],
      ] },
      { type: 'h2', text: 'How it works' },
      { type: 'list', items: [
        'Create your SureXend wallet and complete KYC for your country.',
        'Deposit USDC from any wallet or exchange.',
        'Convert to your local currency at a live rate.',
        'Withdraw to your bank or mobile money, or spend on bills and airtime.',
      ] },
      { type: 'callout', title: 'Built for the whole continent', text: 'The goal is simple: USDC should be as easy to spend in Accra or Nairobi as it is in Lagos. No cross-border friction, no corridor lock-in.' },
      { type: 'h2', text: 'Freelancers & remote teams' },
      { type: 'p', text: "If your clients pay in dollars or USDC, SureXend lets you hold that value safely and convert only what you need — so your income stops losing value to local currency inflation while it sits waiting." },
    ],
    faq: [
      { q: 'Can I withdraw USDC to mobile money?', a: 'In supported countries, yes. Kenya and Ghana support mobile money payouts alongside bank transfers.' },
      { q: 'Does SureXend work in Kenya, Ghana and South Africa?', a: 'Yes. Each country gets local-currency support, local payout rails and local bill options where available.' },
      { q: 'How is the exchange rate set for my country?', a: 'SureXend uses a live market rate for each local currency and shows it to you before you confirm any conversion.' },
      { q: 'Do I need KYC to convert crypto to cash?', a: 'Yes. Like any regulated financial service, a short KYC verification is required to withdraw to bank or mobile money.' },
      { q: 'Is crypto cashout legal in African countries?', a: 'Regulations vary by country, but crypto and stablecoins are broadly legal for personal use. SureXend follows the rules in each market it operates in.' },
    ],
    ctaTitle: 'Your USDC, useful across Africa',
    ctaText: 'Create a wallet, deposit USDC, and cash out to your local currency.',
    related: ['/nigeria', '/kenya', '/ghana', '/south-africa'],
    datePublished: '2026-03-01',
    dateModified: '2026-08-01',
    author: 'SureXend Editorial',
    readingTime: '5 min read',
    priority: 0.85,
  },
]